# Generated by Django 4.1.7 on 2023-04-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_user", models.CharField(max_length=200)),
                ("last_ip_address", models.CharField(max_length=20)),
                ("last_login", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Energy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produced_energy_in_watt", models.IntegerField()),
                ("consumed_energy_in_watt", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hash", models.CharField(default=None, max_length=32, null=True)),
                ("txId", models.CharField(default=None, max_length=66, null=True)),
            ],
        ),
    ]
