# Generated by Django 4.1.7 on 2023-05-16 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("energia", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminlog",
            name="last_login",
        ),
        migrations.AddField(
            model_name="adminlog",
            name="login_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
